# Generated by Django 2.2.4 on 2019-08-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogUpdater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(help_text='Task name', max_length=120)),
                ('task_uuid', models.UUIDField(blank=True, help_text='Universally unique identifier for task', null=True)),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('log', models.TextField(default='')),
                ('exception', models.TextField(default='')),
                ('finished', models.BooleanField(default=False)),
                ('status', models.IntegerField(choices=[(0, 'FAIL'), (1, 'COMPLETED'), (2, 'PENDING')], default=2)),
            ],
        ),
    ]
